# Generated by Django 2.2.6 on 2019-10-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191029_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'all'), ('cam', 'camera'), ('fla', 'flash'), ('bas', 'base')], default='all', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='postcode',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
