# Generated by Django 2.2.6 on 2019-11-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191029_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LC', 'Lence'), ('DC', 'DSLR Camera'), ('OC', 'Other Camera'), ('AC', 'Accesory')], default='DC', max_length=2),
        ),
    ]
