# Generated by Django 2.2.6 on 2019-11-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191101_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='postcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
