# Generated by Django 2.2.6 on 2019-11-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20191101_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Lence', 'Lence'), ('DSLR Camera', 'DSLR Camera'), ('Other Camera', 'Other Camera'), ('Accesory', 'Accesory')], default='DSLR Camera', max_length=11),
        ),
    ]
