# Generated by Django 2.2.7 on 2019-11-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191030_1530'),
        ('product', '0012_product_brand'),
    ]

    operations = [
    ]
