# Generated by Django 2.2.6 on 2019-11-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Lence', 'Lence'), ('DSLR Camera', 'DSLR Camera'), ('Other Camera', 'Other Camera'), ('Accesory', 'Accesory')], default='DSLR Camera', max_length=13),
        ),
    ]
