# Generated by Django 2.2.7 on 2019-11-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phone_number'),
        ('users', '0002_favourite'),
    ]

    operations = [
    ]
