# Generated by Django 2.2.6 on 2019-11-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20191113_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_postcode',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
