# Generated by Django 2.2.7 on 2019-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.PositiveIntegerField(blank=True, default=0)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('lon', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
            ],
        ),
    ]
